# Generated by Django 2.0.7 on 2018-07-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuites', '0002_auto_20180720_2109'),
        ('users', '0004_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_tuites',
            field=models.ManyToManyField(to='tuites.Tuite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='/img/blank-pic.png', upload_to='', verbose_name='Foto de perfil'),
        ),
    ]
