# Generated by Django 2.0.7 on 2018-07-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180730_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_tuites',
            field=models.ManyToManyField(related_name='liked_by', to='tuites.Tuite'),
        ),
    ]
