# Generated by Django 2.0.7 on 2018-07-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='Tweet')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
