# Generated by Django 2.0.7 on 2018-07-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tuite_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuite',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Tuite',
        ),
    ]
